---

apiVersion: v1
kind: Service
metadata:
    name: nginx
    namespace: default

spec:
  selector:
    app: node
  type: NodePort
  ports:
    - nodePort: 30000
      port: 80
      protocol: TCP
      targetPort: 80